aplicationYmlSetup:
  # Discovery Server Access
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:1111/eureka/

  # HTTP Server (Tomcat) Port
  server: 
    port: ${port}

  # Disable Spring Boot's "Whitelabel" default error page, so we can use our own
  error:
    whitelabel:
      enabled: false


